### ISSUE TITLE
Cannot import `mbgl-renderer` installed from `npmjs`

### ISSUE THREAD

**Issue by ka7eh** [consbio/mbgl-renderer#10]
`main` entry in `package.json` (https://github.com/consbio/mbgl-renderer/blob/master/package.json#L5) is pointing to a non-existing file. Changing it to `dist/index.js`  fixes the issues.

**Comment by normanrz** [comment]
This is not an issue for me.

**Comment by brendan-ward** [comment]
This has been fixed
