### ISSUE TITLE
How to increase DPI ?

### ISSUE THREAD

**Issue by abraztsov** [consbio/mbgl-renderer#13]
Now exported images has very low quality. Any idea how to increase dpi ?

**Comment by brendan-ward** [comment]
What image tile sources are you using in your style?  

By default, pixels should render pixel-for-pixel in the underlying tiles.  If you resize the image afterward, it will degrade the quality.  

If you use a floating point zoom level for an image tile source, it will effectively overzoom the tiles when you are between zoom levels, which may also look less than adequate.

If you use a zoom level beyond the zoom levels available for a tile image source, but specify a higher `maxzoom` for the layer(s) that use those sources, it will also overzoom the images, and could look quite poor.

**Comment by abraztsov** [comment]
I'm using mapbox styles (via `mapbox://...`)

**Comment by abraztsov** [comment]
Overall it's looking like this one `dist/cli.js mapbox://styles/foo/bar test.png ...`

I know there's a trick how to render mapbox map in high resoultion on client. Maybe somehow it's possible to render in high res on server using mapbox style?

```
Object.defineProperty(window, 'devicePixelRatio', {
  get: function() {
    return 95 / dpiYouWant;
  }
});

var img = map.getCanvas().toDataURL('image/png');
```

**Comment by aliir74** [comment]
I'm using 100000 for ratio option but my images are low quality:
image version:
![image](https://cdn.pbrd.co/images/HVLTq7i.png)

render version:
![render](https://cdn.pbrd.co/images/HVLT2nn.png)

**Comment by aliir74** [comment]
This problem was sth related to mapbox-gl-js raster tile showing not mbgl-render, Thanks.
