### ISSUE TITLE
Rendered image bigger than mapbox map

### ISSUE THREAD

**Issue by abraztsov** [consbio/mbgl-renderer#14]
It's seems like rendered map displaying more than mapbox map.

Rendered map
<img width="406" src="https://user-images.githubusercontent.com/19175580/48348857-9178e380-e693-11e8-8790-55a157b8917c.png">

Mapbox map
<img width="406" src="https://user-images.githubusercontent.com/19175580/48348888-ae151b80-e693-11e8-9b27-0e732c1e05cd.png">

Test data to render

```
center: [-74.00597279985095, 40.712987756357364],
zoom: 15.1,
height: 1800px,
width: 1350px
```

**Comment by brendan-ward** [comment]
@abraztsov how are you creating the mapbox map?  The [Mapbox Static API Playground](https://www.mapbox.com/help/static-api-playground/) doesn't accept the parameters you have here.

Is the problem with the image dimensions not matching your input width and height, the image dimensions not matching what you get from mapbox, or the area of the world contained within the map being different?

**Comment by brendan-ward** [comment]
@abraztsov I discovered the issue - we were originally treating zoom level as an integer instead of floating point value.  That is now fixed and my local results now match your mapbox image.
