### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by beyoung** [consbio/mbgl-renderer#15]
I clone this project, and run 
```shell 
npm install
```
It appears:
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v4.0.0-pre.13/node-v51-linux-x64-Release.tar.gz

**Comment by beyoung** [comment]
After read mapbox-native-gl issues [Npm install failing with 403 error](https://github.com/mapbox/mapbox-gl-native/issues/12667), I found solution to fix it.

**Comment by klongmitre** [comment]
@beyoung - I'm hitting the same wall. What was your solution for this?

**Comment by brendan-ward** [comment]
@klongmitre note that we do not recommend Node 10 yet, per this in the README:

> WARNING: note that Node 10 may have issues, and crash. See: https://github.com/mapbox/mapbox-gl-native/issues/12252 Until that issue is closed, we recommend using Node 8.

What version of Node are you trying to use?
