### ISSUE TITLE
Maximum number of ratio that supported?

### ISSUE THREAD

**Issue by aliir74** [consbio/mbgl-renderer#22]
Hi. What is the maximum number of ratio that supported? I want to set this blurriness in retinal displays

**Comment by brendan-ward** [comment]
@aliir74 I don't see that this is documented in the Mapbox GL documentation, though it looks like in practice this is usually between 1 and 3.  For retina displays, I thought the appropriate ratio is 2.

This will likely require manual testing to see how it fits your needs.  If you test this, please report back, and we can add notes about it here.

**Comment by brendan-ward** [comment]
Resolved via comment in README: 30514e992b7c70952ed2bc140a51ef4dc12a0b76
