### ISSUE TITLE
mbgl-render didn't use local mbtiles

### ISSUE THREAD

**Issue by aliir74** [consbio/mbgl-renderer#23]
I use raster png files as mbtiles but my picture is empty
```
mbgl-render -r 1 -c 51.388,35.7026228 -z 12 -t /home/ali/disk2/tiles/raster ~/Programming/map/TileProvider/dynamic/style_raster_test.json test.png 512 512 
```

**Comment by brendan-ward** [comment]
@aliir74 can you share your `style_raster_test.json` so that we can see how you are referring to your local mbtiles file(s) from there?

**Comment by brendan-ward** [comment]
@aliir74 very sorry for the delayed response.  Your `source` needs to point to a URL (not a `file://`).

To use local mbtiles from your tiles directory, see this example:
https://github.com/consbio/mbgl-renderer/blob/master/tests/fixtures/example-style-mbtiles-source.json

using the `mbtiles://` syntax to create direction your mbtiles file.

Alternatively, you can point it at tiles instead, per this example: https://github.com/consbio/mbgl-renderer/blob/master/tests/fixtures/example-style-mbtiles-tiles.json

**Comment by aliir74** [comment]
Hi @brendan-ward, Thanks for your reply.

I used below command:
```
mbgl-render -r 1 -c 51.388,35.7026228 -z 12 -t /home/ali/disk2 ~/Programming/map/TileProvider/dynamic/style_raster_test.json test.png 512 512
```
with this style file:
```
"sources": {
    "high_update": {
      "type": "raster",
      "tileSize": 256,
      "tiles": [
        "mbtiles://tiles/raster/{z}/{x}/{y}.png"
      ],
      "minzoom": 3,
      "maxzoom": 19
    }
  },
  "layers": [
    {
        "id": "simple-tiles",
        "type": "raster",
        "source": "high_update",
        "minzoom": 4,
        "maxzoom": 20
    }
  ],
```
But error happened:
```
➜  TileProvider git:(master) ✗ mbgl-render -r 1 -c 51.388,35.7026228 -z 12 -t /home/ali/disk2 ~/Programming/map/TileProvider/dynamic/style_raster_test.json test.png 512 512     


-------- Export Mapbox GL Map --------
style: "/home/ali/Programming/map/TileProvider/dynamic/style_raster_test.json"
output image: test.png (512w x 512h)
using local mbtiles in: /home/ali/disk2
Error: Mbtiles file mbtiles://tiles.mbtiles in style file is not found in: /home/ali/disk2
    at /home/ali/.config/yarn/global/node_modules/mbgl-renderer/dist/render.js:401:27
    at Array.forEach (native)
    at /home/ali/.config/yarn/global/node_modules/mbgl-renderer/dist/render.js:398:33
    at render (/home/ali/.config/yarn/global/node_modules/mbgl-renderer/dist/render.js:332:12)
    at renderRequest (/home/ali/.config/yarn/global/node_modules/mbgl-renderer/dist/cli.js:122:24)
    at /home/ali/.config/yarn/global/node_modules/mbgl-renderer/dist/cli.js:169:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
```

My tiles are in this address: `/home/ali/disk2/tiles/raster/{z}/{x}/{y}.png`

**Comment by brendan-ward** [comment]
@aliir74 are your tiles stored as individual PNG files on disk, or are they stored within an `mbtiles` file?   If the former, we don't support the use case, you would need to put a tile server in front of your tiles rather than fetching straight from disk.

In theory, someone could develop and add the functionality to use tiles directly from disk in the way you are trying to do here, but that is not something I'm available to tackle right now.

the `mbtiles://` source is a convenience method for connecting directly to an `mbtiles` file (spec here: https://github.com/mapbox/mbtiles-spec) on disk, since we have a known pathway for querying all information we need about the tileset from the `mbtiles` file.

**Comment by aliir74** [comment]
@brendan-ward Thanks.

I convert my directory to an mbtiles file with `mb-util` but this error happened:
```
-------- Export Mapbox GL Map --------
style: "/home/ali/Programming/map/TileProvider/dynamic/style_raster_test.json"
output image: test.png (512w x 512h)
using local mbtiles in: /home/ali/disk2/tiles/
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error rendering map: {}
Error: Cannot read property 'slice' of null
    at Error (native)
```
This is my style file:
```
"sources": {
    "high_update": {
      "type": "raster",
      "tileSize": 256,
      "tiles": [
        "mbtiles://high-mb"
      ],
      "minzoom": 3,
      "maxzoom": 19
    }
  }
```
and `high-mb.mbtiles` is an file in `/home/ali/disk2/tiles`.
I also try with an independent mbtiles to prevent probable `mb-util` bug but same error happened.

**Comment by brendan-ward** [comment]
@aliir74 would you mind testing with the example from the readme, to verify that `mbgl-renderer` is working properly except for your `mbtiles` files?

`mbgl-render tests/fixtures/example-style-mbtiles-source-vector.json test.png 1024 1024 -z 0 -c 0,0 -t tests/fixtures`

From the above errors, it looks like it is unable to properly retrieve tiles from the `mbtiles` file.  We did not test with any tiles created using `mb-util`, so it is possible that there is something unexpected about the tile structure in the `mbtiles` file.  Are you able to post a small `mbtiles` file you generated for us to test with?

**Comment by aliir74** [comment]
Hi dear @brendan-ward, Sorry for my delay.

This is a sample of my mbtiles [https://ufile.io/7tm5x]()
I also buy a mbtiles from [https://openmaptiles.com]() and same error happened.

**Comment by aliir74** [comment]
Seems this issue is relevant to mb-util problem. and also openmaptiles site have raster tiles that didn't support in your project, right?

**Comment by aliir74** [comment]
Hi again @brendan-ward. I created correct mbtiles but the same error heppend. I uploaded my mbtiles for your test, [high_update tiles](https://ufile.io/5km6e) and [low_update tiles](https://ufile.io/twxnn).
The error:
```
➜  dynamic git:(WebView) ✗ mbgl-render style_preview.json test.png 512 512 -c 51.388,35.7026228 -z 16 -r 1 -t ~/disk2/tiles


-------- Export Mapbox GL Map --------
style: "style_preview.json"
output image: test.png (512w x 512h)
using local mbtiles in: /home/ali/disk2/tiles
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error while making tile request: {}
Error rendering map: {}
Error: Cannot read property 'slice' of null
    at Error (native)
```
My style file:
```
"sources": {
    "high_update": {
      "type": "vector",
      "tiles": [
        "mbtiles://high-very-little"
      ],
      "minzoom": 3,
      "maxzoom": 16
    },
    "low_update": {
      "type": "vector",
      "tiles": [
        "mbtiles://low-very-little"
      ],
      "minzoom": 3,
      "maxzoom": 16
    }
  }
```

Thanks for your work on my problem. This is very important to me and my team to render map from local tiles for faster speed of render.

**Comment by aliir74** [comment]
I changed my style address to below and the code worked. Thanks for your support!
```
"sources": {
    "high_update": {
      "type": "vector",
      "tiles": [
        "mbtiles://high-very-little/{z}/{x}/{y}"
      ],
      "minzoom": 3,
      "maxzoom": 16
    },
    "low_update": {
      "type": "vector",
      "tiles": [
        "mbtiles://low-very-little/{z}/{x}/{y}"
      ],
      "minzoom": 3,
      "maxzoom": 16
    }
  }
```
