### ISSUE TITLE
GeoJSON overlay

### ISSUE THREAD

**Issue by hcphoon01** [consbio/mbgl-renderer#34]
I see there is the ability to add GeoJSON overlays to a map before its rendered but only in a JSON file, is it possible to add the overlays to a style from mapbox?

**Comment by brendan-ward** [comment]
@hcphoon01 there isn't a way to do this in terms of a named style with the APIs we have in place now.

However, one way around this would be to create a JSON style file that overlays your GeoJSON over raster tiles from a given Mapbox style.  Docs: https://docs.mapbox.com/help/glossary/raster-tiles-api/
