### ISSUE TITLE
Docker images problems

### ISSUE THREAD

**Issue by submarcos** [consbio/mbgl-renderer#40]
As 0.4.0 version is working perfectly, latest version doesn't work as expected.

docker pull consbio/mbgl-renderer:latest
docker run --rm -p 8080:80 consbio/mbgl-renderer

ERROR: Path to mbtiles files does not exist: ./tiles

**Comment by brendan-ward** [comment]
@submarcos thank you for reporting this!

The issue was due to extra validation we added recently.  This will be fixed once the new image is done building on Docker hub.

**Comment by submarcos** [comment]
thank you !
