### ISSUE TITLE
Cannot read property 'GET' of undefined

### ISSUE THREAD

**Issue by LePetitTim** [consbio/mbgl-renderer#43]
Using latest version with docker , I get an error which stop the server:
```
/app/dist/server.js:265
    server.router.routes[method].forEach(function (_ref) {
                        ^

TypeError: Cannot read property 'GET' of undefined
    at /app/dist/server.js:265:25
    at Array.forEach (<anonymous>)
    at /app/dist/server.js:264:11
    at nextTick (/app/node_modules/restify/lib/chain.js:165:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
I do
```
docker pull consbio/mbgl-renderer:latest
docker run --rm -p 8080:80 consbio/mbgl-renderer
```
It happens when i am connecting to the root. http://mbglrenderer/ for example .

It was working in 0.4.0 :
```{"routes":{"/render":["GET","POST"],"/":["GET"]}}```

**Comment by brendan-ward** [comment]
Thanks for reporting @LePetitTim and sorry for the issues!

I suspect this was introduced during our upgrade of `restify` in f73f32fd515fd0997440cff740b9353901660f47

The bigger issue is that once you hit a route that doesn't exist, the server (at least in Docker) no longer accepts any incoming requests.  Obviously a bad thing.

I'll work on a fix.

**Comment by brendan-ward** [comment]
Yeah, this was due to an API change in `restify`: https://stackoverflow.com/a/57569241

Fix coming up.
