### ISSUE TITLE
Add fitbounds padding

### ISSUE THREAD

**Issue by LePetitTim** [consbio/mbgl-renderer#45]
It would be great to be able to add padding using fitbounds.

**Comment by brendan-ward** [comment]
@LePetitTim I need more to go on to understand what you are looking for.

We calculate center and zoom from bounds here: https://github.com/consbio/mbgl-renderer/blob/master/src/render.js#L353-L366

In a different project, I've added bounds handling around this same kind of usage: https://github.com/consbio/mbgl-renderer/blob/master/src/render.js#L353-L366

Are you suggesting that we add a `padding` to all of the APIs (Node, HTTP, CLI), or is there one you had in mind?

**Comment by LePetitTim** [comment]
The idea was to be able to use padding on all of the APIs.

**Comment by LePetitTim** [comment]
For example :
We could use fitBoundsOptions.
We could change mapbox/viewport to uber-common/viewport-mercator-project which add options padding and offset.
I don't know which solution is possible and easiest to do.
I tried both of them and didn't get any valuable solution.

**Comment by brendan-ward** [comment]
@LePetitTim 
What do you mean by this?
> I tried both of them and didn't get any valuable solution.

If I were doing this, I'd probably continue using mapbox/viewport and the addition from another project I linked above - to keep things simple, and not add another dependency.

**Comment by LePetitTim** [comment]
> @LePetitTim
> What do you mean by this?
> 
I tried to do it in my own project, both solutions. I changed mapbox/viewport totally to use the uber-common/viewport-mercator-project.

I tried to Add the option fitBoundOptions which didn't work. I can still create a Pull request, if anyone have an idea how to fix my code.

**Comment by LePetitTim** [comment]
_We could use fitBoundsOptions._ = > We can't, the option doesn't exist.
_We could use uber-common/viewport-mercator-project_ => I couldn't make it works, i am not able to do it.

**Comment by brendan-ward** [comment]
@LePetitTim I have some ideas about how we could add that functionality here, by surfacing a `padding` option to all the APIs, and use that to zoom out the zoom level we get back from `@mapbox/geo-viewport` (the implementation would be the second link I posted above, but more work here to expose via APIs).  I just haven't had a chance yet.  I'll try to get to it in the next few days.

Apologies if this is holding you up.  If you need something sooner, you can use the approach from the second link above in your own code to calculate a zoom and centerpoint that you pass in to whichever of the APIs you are using from `mbgl-renderer`.

**Comment by brendan-ward** [comment]
@LePetitTim  see updated usage in `README.md`, padding is now an option for all interfaces.
