### ISSUE TITLE
Rendering weirdness with Nextzen vector tiles

### ISSUE THREAD

**Issue by durkie** [consbio/mbgl-renderer#47]
Nextzen (formerly Mapzen) has hosted vector tiles (details at https://www.nextzen.org), that are basically free (an open S3 bucket and you only pay for the data transfer), but I'm having trouble getting them to render correctly in mbgl-render.

Making a static map with bounds `-96.1767551,29.044431,-75.1325,37.57731` looks quite bad with nextzen tiles:
![image](https://user-images.githubusercontent.com/3200608/72467101-3f0be900-37a8-11ea-9bb0-dbac829d087b.png)

compared to mapbox:
![image](https://user-images.githubusercontent.com/3200608/72467226-7da1a380-37a8-11ea-91de-0a2713a9e5e4.png)

i think a lot of the problems come from styling issues and layer names, especially since mbgl-render gives no errors, but I'd love for someone else to take a look at this too.

the nextzen tiles are functional, at least as far as ogr2ogr and mapbox gl js are concerned: you can add the nextzen tiles as a tile source in mapbox gl js and expected features are visible. likewise, ogr2ogr can convert the tiles to other geometry formats. 

one strange thing I see with these tiles is that they seem to be simplified at 1 zoom level lower than mapbox: 

mapbox:
![image](https://user-images.githubusercontent.com/3200608/72490393-279f2100-37e5-11ea-807b-f17d0976bf52.png)

nextzen:
![image](https://user-images.githubusercontent.com/3200608/72490398-2b32a800-37e5-11ea-8e7b-c5c4b1f96305.png)

but all the geometries are there:
nextzen overlay on mapbox:
![image](https://user-images.githubusercontent.com/3200608/72490460-46051c80-37e5-11ea-840a-282c74b4f815.png)

zoom in and the geometries smooth out:
![image](https://user-images.githubusercontent.com/3200608/72490472-4ef5ee00-37e5-11ea-8672-ee05c33b2933.png)

styles with these tiles have to be adjusted some because there is a `roads` and `transit` layer instead of a `road` or `transportation` layer but `water`, `places`, `boundaries`, `landuse`, and `pois` are there with their usual name. no `mvt_id` attribute, but that doesn't seem to matter. and a `kind` and `kind_detail` attribute on each object instead of mapbox's `class` and `type` attributes.

it'd be lovely to be able to use these tiles. i think their most recent build is from july of 2019, but that's fine for my purposes. i regularly need to generate many static maps and i'd love to cache them. all other mapping providers forbid this.

some of the issues with water/parks I think is manageable with tweaking the style, but any ideas about what to do about geometry simplification? it's almost like you have to request 1 zoom higher with these tiles than with mapbox.

**Comment by brendan-ward** [comment]
@durkie thanks for reporting this issue.  Can you share your style JSON here?  Or at least
how you are configuring the `source` for nextzen (esp. the tile URL and tile size).

They list tile endpoints for 2 different sizes:
https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.mvt?api_key=your-nextzen-api-key
https://tile.nextzen.org/tilezen/vector/v1/256/all/{z}/{x}/{y}.mvt?api_key=your-nextzen-api-key

I could see potential issues if you are using a different tile size endpoint than you have configured for your `source` in your style JSON.

**Comment by durkie** [comment]
Sure. I've attached my style.json here: https://gist.github.com/durkie/4343a40c7e5c33eea6c9e169fa1982a6

It's basically the openmaptiles "basic" style that I've been adapting to work with these Nextzen tiles, so still very much a work in progress.

I have not been using a `tileSize` parameter: the mapbox style spec made it sound like it was only relevant to raster tiles. Testing it now it does not seem to make a difference in the output: requesting the 512 tiles with `tileSize: 256`, `tileSize: 512`, or even `tileSize: 8192` all look identical.

There are some visible differences between using the 256 tiles versus the 512 tiles:

256:
![image](https://user-images.githubusercontent.com/3200608/72493786-efe9a680-37ef-11ea-92fd-3b9bbf02bbd9.png)

512 (extra lakes visible, more coastline detail, better resolution of greenspace boundaries):
![image](https://user-images.githubusercontent.com/3200608/72493791-f4ae5a80-37ef-11ea-8984-e24edd64442f.png)

--

256:
![image](https://user-images.githubusercontent.com/3200608/72493916-4951d580-37f0-11ea-8865-76435f339d83.png)


512 (less simplification, some more features visible):
![image](https://user-images.githubusercontent.com/3200608/72493918-4d7df300-37f0-11ea-85d9-d7791b5bc63d.png)

**Comment by brendan-ward** [comment]
The issue seems partly related to needing to use geometry type filters for the layers:

Example style:
```
{
    "version": 8,
    "sources": {
        "basemap": {
            "type": "vector",
            "tiles": [
                "https://c.tile.nextzen.org/tilezen/vector/v1/256/all/{z}/{x}/{y}.mvt?api_key=<API KEY>"
            ],
            "tileSize": 256,
            "maxzoom": 16
        }
    },
    "layers": [
        {
            "id": "water-fill",
            "type": "fill",
            "source": "basemap",
            "source-layer": "water",
            "filter": ["==", "$type", "Polygon"],
            "paint": {
                "fill-color": "#0000FF",
                "fill-opacity": 1
            }
        },
        {
            "id": "water-outline",
            "type": "line",
            "source": "basemap",
            "source-layer": "water",
            "filter": ["==", "$type", "LineString"],
            "paint": {
                "line-color": "#FF0000",
                "line-opacity": 1,
                "line-width": 2
            }
        }
    ]
}
```

produces this image:

![test](https://user-images.githubusercontent.com/3375604/72494474-d1c47c00-37d8-11ea-8fcd-e73f8ec13ac7.png)

Without the `filter` statements, the result is roughly similar to your first example.



Possibly helpful for working out the style: 
https://github.com/stevage/portable-vector-style/blob/master/out/kbasic-mapzen.json
https://github.com/klokan/tilezen-gl-style

**Comment by brendan-ward** [comment]
Yeah, I think that's it. Your style has geometry type filters in some places, but not everywhere you likely need them.

Example: you need to use a polygon filter here: https://gist.github.com/durkie/4343a40c7e5c33eea6c9e169fa1982a6#file-basic-json-L296

Sorry for misleading you on the tile size.

Not sure why the levels of detail differ between Mapbox and Nextzen, but probably has a lot to do with how they generated the tiles.

Since this looks like a style issue rather than a bug with `mbgl-renderer` I'm going to close this.  If you do run into a bug on our end using Nextzen tiles, please feel free to reopen.

**Comment by durkie** [comment]
Yep, thanks for your help! Looks much better with a tilezen specific style...sometimes you get so stuck in a problem you can't think of other ways to solve it :)

![image](https://user-images.githubusercontent.com/3200608/72561020-3c77c500-3876-11ea-8003-d52083016796.png)
