### ISSUE TITLE
Slow performance when rendering complex environments

### ISSUE THREAD

**Issue by d3alek** [consbio/mbgl-renderer#66]
I am using the Docker mbgl-renderer server, making 400x400 images. The response for rendering a city-wide view takes 1.5 seconds, which for my use case is too slow. Bigger zoom gets me down to 200ms, which is slow but passable. What can I do to speed up the server response?

My style.json:
```
{
    "sources": {
        "mytiles": {
            "type": "vector",
            "tiles": "mbtiles://tiles/{z}/{x}/{y}.pbf"
        },
        "layers": {
            ... # standard OpenMapTiles layers
        )
}
```

OpenMapTiles layers configuration is from [here](https://github.com/systemed/tilemaker/blob/master/resources/config-openmaptiles.json)

**Comment by brendan-ward** [comment]
@d3alek what zoom level are you using for city-wide view and for bigger zooms?

The primary thing that comes to mind is that more features of more layers are being rendered at city-wide view than at other views.  This depends heavily on which layers are visible at that zoom, how many features are in view for each layer, how complex those features are, and how complex your style is.  One way to troubleshoot that is to comment out all of your layers, and then incrementally add them back while tracking performance.

If that is the case, then the performance is most likely not under our control in this project, but rather an issue with the larger `mapbox-gl` project.  One thing to note here is that unlike frontend-oriented versions (`mapbox-gl-js`), this does not leverage your GPU card if available, so I would expect it to be slower for the same tiles / style than rendering this in the browser (which can leverage your GPU).

Note: `tiles` in your style should be an array (see [docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/)):
```
...
"tiles": ["mbtiles://tiles/{z}/{x}/{y}.pbf"],
...
```


Also - is the 200ms baseline the time to render the response on the server, or is it the full round-trip time of making the request against your server?  Are you making requests to `mbgl-renderer` server from your local server or somewhere else?

**Comment by d3alek** [comment]
Thank you for the advice - leaving only `transportation` layers in improved baseline performance down to 100ms. This is good enough for my use case.
