### ISSUE TITLE
windows 10 install error

### ISSUE THREAD

**Issue by prasadrajuv** [consbio/mbgl-renderer#68]
> @mapbox/mapbox-gl-native@5.0.2 install E:\mbgl\node_modules\@mapbox\mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v64-win32-x64-Release.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (E:\mbgl\node_modules\node-pre-gyp\lib\install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (E:\mbgl\node_modules\request\request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:441:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\mbgl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd E:\mbgl\node_modules\@mapbox\mapbox-gl-native
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v64-win32-x64-Release.tar.gz
npm WARN enoent ENOENT: no such file or directory, open 'E:\mbgl\package.json'
npm WARN mbgl No description
npm WARN mbgl No repository field.
npm WARN mbgl No README data
npm WARN mbgl No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mapbox/mapbox-gl-native@5.0.2 install: `node-pre-gyp install --fallback-to-build=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @mapbox/mapbox-gl-native@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\prasad\AppData\Roaming\npm-cache\_logs\2020-12-25T04_33_25_472Z-debug.log

**Comment by brendan-ward** [comment]
According to the error log, the failure is due to a pre-compiled version of `mapbox-gl-native` not being available for your platform, and the fallback to compiling from source failed.  Looking at that repo, Windows is not a supported platform.

Please consider using Docker to provide this on Windows.  Images are available on Docker Hub at `https://hub.docker.com/r/consbio/mbgl-renderer`
