### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by brendan-ward** [consbio/mbgl-renderer#7]
Example of a very similar build: https://github.com/klokantech/tileserver-gl/blob/master/Dockerfile

**Comment by jdbohrman** [comment]
I would love to help with this!

**Comment by brendan-ward** [comment]
@jdbohrman some help would be greatly appreciated!  

I started some initial work on this front in the `add-docker` branch: https://github.com/consbio/mbgl-renderer/blob/add-docker/docker/Dockerfile

But have not had a chance to see this all the way through.  Part of the problem was the long builds due to `apt-get` installs, which are not fun on slower internet connections.

One of the gotchas to watch for is making sure that Xvfb is up and running.  Our current `entrypoint.sh` (https://github.com/consbio/mbgl-renderer/blob/add-docker/docker/entrypoint.sh) is copied from another similar project but hasn't been totally worked out for this one.

From a functionality standpoint, having `mbgl-server` available in the container is the most important and likely most common use case.  I don't know that it will be as common for folks to run `mbgl-render` against the container, though it would be a nice to have.

**Comment by jdbohrman** [comment]
@brendan-ward What made you guys go with an Ubuntu base image as opposed to Node?

**Comment by brendan-ward** [comment]
@jdbohrman no particular reason other than wanting to try out the new minimal Ubuntu image.  Our other project used the Node base image, so that would probably be a better starting point - I just hadn't tried that yet.

**Comment by jdbohrman** [comment]
@brendan-ward Awesome! Yeah I agree that would likely be better. What were the issues you were having with Xvfb?

**Comment by brendan-ward** [comment]
@jdbohrman No issues with Xvfb, it just needs to be up and running in order to render anything, or you will get errors.  The `entrypoint.sh` has a working setup for using it from another project, I just didn't have a chance yet to fully integrate and test it here.  May not require much modification at this point.

**Comment by jdbohrman** [comment]
@brendan-ward I had an interesting solution suggested to me about your long build times with apt-get. You could download the binaries for the packages you're installing and call something like `COPY somepackage.deb somepacke.deb` and then `RUN dpkg -i somepackage.deb`.

**Comment by jdbohrman** [comment]
Another idea is using multi-stage builds

**Comment by jdbohrman** [comment]
https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

**Comment by brendan-ward** [comment]
@jdbohrman thanks for looking into the alternatives!

I'm concerned about the labor involved in the first solution you suggest: I think there are a lot of dependencies that we'd have to manage that way, and the filenames all have their version in them, so a potential maintenance issue...  Interesting idea though, might work well for projects where there are just a few.

I'm not sure that multi-stage builds would help here, but that could just be based on me misunderstanding the nature of the docs for those.  In our case, we don't need multiple base images, where we use one to build the binary artifacts of the application, and then copy those binaries into the final image (my understanding of the example).

In our case, we need a bunch of those libraries available since I think they are dynamically rather than statically linked into the mapbox gl native stuff used underneath mapbx gl native node.

I wonder if there is a third option: creating a new image that contains all (or most of) the build dependencies (perhaps based off the Node base image), and post that to dockerhub.  Then we would simply use that as our base image here, and then our Dockerfile would just need to focus on running npm / yarn install for mapbox gl native and our other direct node dependencies in `package.json`?

**Comment by roblabs** [comment]
I've got some progress on the docker, but I've ran into some issues.  I'm mostly interested in the feature `mbgl-render`, and I wanted to publish my progress to date.  

I'm currently serving `mbtiles` using `tileserver-gl` and then pulling PNGs out of the browser.  See http://www.roblabs.com/print-maps 

Figuring out how to build `mapbox-gl-native` with Docker was worth a day of trials.  So, what I leave as of this writing may be worth while for others interested in Docker + `mapbox-gl-native`.  I'm leveraging heavy off of [klokantech/tileserver-gl](https://github.com/klokantech/tileserver-gl) and @brendan-ward's notes above.

---

### Status

- [x] Hosted at Docker Hub, pull down with `docker pull roblabs/mbgl-renderer`
- [x] https://hub.docker.com/r/roblabs/mbgl-renderer/
- [x] Built with `ubuntu:xenial`, will roll to `ubuntu:bionic` after its functional
- [x] `mapbox-gl-native` is built and all the build libraries are included.  Includes `yarn`.
- [ ] **Issue** Need to figure out how the X Display should work with command line & `Xvfb`
```
-------- Export Mapbox GL Map --------
style: "tests/fixtures/example-style-mbtiles-source-vector.json"
output image: test.png (1024w x 1024h)
using local mbtiles in: tests/fixtures
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open X display.
```
- [ ] **Issue** Needs integration with hosts command line, e.g., I would like to run it as `docker run --rm -it -v "$(pwd)":/data roblabs/mbgl-renderer <options>` 
- [ ] **TODO** Needs integration with `mbgl-server`
- [ ] `consbio/mbgl-renderer` should be considered the master once it's functional

- [ ] **TODO** Should include `jest` and `babel` for tests
```
RUN npm install babel-cli babel-preset-es2015 jest
RUN yarn test
```

- [ ] **Issue** Other Dockerfile items to include.  These did not work, but they may work for `mbgl-server`
```
ENTRYPOINT ["/bin/bash", "/usr/src/app/entrypoint.sh"]
RUN mkdir -p /usr/src/app
ADD entrypoint.sh /usr/src/app
```
