### ISSUE TITLE
DPI on exported PNG

### ISSUE THREAD

**Issue by techmavengeospatial** [consbio/mbgl-renderer#70]
I don't see anywhere in the documentation (could have missed it ) the DOTS PER INCH (DPI)
in order to convert page size to Pixel size I need to know DPI
is it 96DPI ? is there some setting?

12 X 18  ARCH B  1152 px 1728 px
13 X 19 or 19 x 13  1248 px 1824 px
18.0 x 24.0 in or 24x 18  ARCH C  1728 px  2304 px
24x36 or 36 x 24 ARCH D  2304 px 3456 px

Is there any issue creating Arch D or Even Arch E 36 " x 48 " export?
We are looking to setup a map printing service

**Comment by brendan-ward** [comment]
There is no direct DPI setting for this project or the underlying rendering library; you need to scale the output resolution to meet your need (controlled via `width`, 'height`, and `ratio` parameters).

See `ratio` parameter in particular for controlling pixel ratio (documented in the README) for increasing the resolution of the output image.  See `tests/fixtures/expected-mapbox-source.png` and `tests/fixtures/expected-mapbox-source@2x.png` for examples of the output of using this setting the ratio to 2 (test of this is [here](https://github.com/consbio/mbgl-renderer/blob/0.7.2/tests/render.test.js#L319-L336)).

See #46 for some of the constraints around max image size that can be produced by this library using Docker (very large images directly on the hosts has not been tested); if you need big images you will need to render them in chunks and merge them together.

For print please make sure to include appropriate attribution as required by the basemap providers (e.g., Mapbox terms documented [here](https://docs.mapbox.com/help/how-mapbox-works/attribution/#static--print)).  😄

**Comment by techmavengeospatial** [comment]
Thanks for the reply
we are NOT using any MapBox data or services
we self host our own created vector tiles as well as OpenMapTiles.com OSM Data
Yes, We will handle all legal requirements for this and provide proper attribution.
